### PR TITLE
Close redis connection when the faye client is garbage collected.

### PR DESCRIPTION
**Pull request by FabienChaynes**
The gem is leaking a redis connection (props to @spuyet for discovering it).

When a faye client using `Faye::Authentication::ClientExtension` is not referenced anymore and thus garbage collected, the redis client is never closed.

This PR fixes this by attaching a finalizer to the client. When it'll be destroyed, the proc will be run and will close the connection, thus avoiding the leak.

### CODE REVIEW

**Review by jarthod — APPROVED** [review]
Looks good to me, any reason to have a class method instead of just a lambda in the finializer line?

**Comment by FabienChaynes** [comment]
Yes. A lambda would hold a reference to `self` (the faye client) so it'd never be garbage collected. It's explained in [this blog post](http://www.mikeperham.com/2010/02/24/the-trouble-with-ruby-finalizers/).

```ruby
[31] pry(main)> class A
[31] pry(main)*   def test
[31] pry(main)*     proc { puts self.inspect }
[31] pry(main)*   end  
[31] pry(main)* end  
=> :test
[33] pry(main)> A.new.test.call
#<A:0x000055bda4b17878>
=> nil
[34] pry(main)> class A
[34] pry(main)*   def test  
[34] pry(main)*     lambda { puts self.inspect }    
[34] pry(main)*   end  
[34] pry(main)* end  
=> :test
[35] pry(main)> A.new.test.call
#<A:0x000055bda4c46168>
=> nil
```

**Comment by jarthod** [comment]
Haha nice, good point. I expected something like that but didn't knew. Worth sharing with the team IMO :)

**Comment by spuyet** [comment]
Nice job @FabienChaynes :+1:

**Comment by FabienChaynes** [comment]
Merged in 448d249d32dc29723f5a50c16db4dbebaf6213ae.

**Pull request closed without merging**
